#!/usr/bin/env npx ts-node
/**
 * Build script for Sample Client
 * 
 * This script:
 * 1. Reads CDK outputs to get Cognito and CloudFront configuration
 * 2. Generates .env.production with the correct URLs
 * 3. Builds the sample client with production configuration
 * 
 * Usage:
 *   npx ts-node scripts/build-sample-client.ts
 *   
 * Or after making it executable:
 *   ./scripts/build-sample-client.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

interface CdkOutputs {
  TheSafeZoneIdpStack: {
    SampleClientId: string;
    CognitoDomain: string;
    CognitoDomainUrl: string;
    SampleClientUrl?: string;
    LoginUiUrl?: string;
  };
}

const SAMPLE_CLIENT_DIR = path.join(__dirname, '../../sample-client');
const CDK_OUTPUTS_FILE = path.join(__dirname, '../cdk-outputs.json');

function main() {
  console.log('🔧 Building Sample Client for production...\n');

  // Check if CDK outputs exist
  if (!fs.existsSync(CDK_OUTPUTS_FILE)) {
    console.error('❌ CDK outputs not found. Run "cdk deploy --outputs-file cdk-outputs.json" first.');
    process.exit(1);
  }

  // Read CDK outputs
  const outputs: CdkOutputs = JSON.parse(fs.readFileSync(CDK_OUTPUTS_FILE, 'utf-8'));
  const stackOutputs = outputs.TheSafeZoneIdpStack;

  if (!stackOutputs) {
    console.error('❌ TheSafeZoneIdpStack outputs not found in cdk-outputs.json');
    process.exit(1);
  }

  const { SampleClientId, CognitoDomainUrl, SampleClientUrl, LoginUiUrl } = stackOutputs;

  if (!SampleClientId || !CognitoDomainUrl) {
    console.error('❌ Missing required outputs: SampleClientId or CognitoDomainUrl');
    process.exit(1);
  }

  // Extract domain from full URL (remove https://)
  const cognitoDomain = CognitoDomainUrl.replace('https://', '');

  // Determine redirect URI - use CloudFront URL if available, otherwise use placeholder
  let redirectUri: string;
  if (SampleClientUrl) {
    redirectUri = `${SampleClientUrl}/callback`;
  } else {
    console.warn('⚠️  SampleClientUrl not found. Using placeholder - redeploy after first deployment.');
    redirectUri = 'https://CLOUDFRONT_URL_PLACEHOLDER/callback';
  }

  // Determine login UI URL for profile editing
  let loginUiUrl: string;
  if (LoginUiUrl) {
    loginUiUrl = LoginUiUrl;
  } else {
    console.warn('⚠️  LoginUiUrl not found. Using localhost fallback.');
    loginUiUrl = 'http://localhost:5173';
  }

  // Generate .env.production
  const envContent = `# Production configuration for Sample Client
# Auto-generated by build-sample-client.ts - DO NOT EDIT MANUALLY

# Cognito User Pool Client ID
VITE_COGNITO_CLIENT_ID=${SampleClientId}

# Cognito Domain (full domain for OAuth2 endpoints)
VITE_COGNITO_DOMAIN=${cognitoDomain}

# Callback URL (CloudFront distribution)
VITE_REDIRECT_URI=${redirectUri}

# Login UI URL for profile editing
VITE_LOGIN_UI_URL=${loginUiUrl}
`;

  const envPath = path.join(SAMPLE_CLIENT_DIR, '.env.production');
  fs.writeFileSync(envPath, envContent);
  console.log(`✅ Generated ${envPath}`);
  console.log(`   - VITE_COGNITO_CLIENT_ID: ${SampleClientId}`);
  console.log(`   - VITE_COGNITO_DOMAIN: ${cognitoDomain}`);
  console.log(`   - VITE_REDIRECT_URI: ${redirectUri}`);
  console.log(`   - VITE_LOGIN_UI_URL: ${loginUiUrl}\n`);

  // Build sample client
  console.log('📦 Building sample client...\n');
  try {
    execSync('npm run build', {
      cwd: SAMPLE_CLIENT_DIR,
      stdio: 'inherit',
    });
    console.log('\n✅ Sample client built successfully!');
    console.log(`   Output: ${path.join(SAMPLE_CLIENT_DIR, 'dist')}\n`);
  } catch (error) {
    console.error('❌ Build failed');
    process.exit(1);
  }

  console.log('🚀 Ready for deployment. Run "cdk deploy" to upload to S3/CloudFront.');
}

main();
